spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/employee/**
        - id: consumerModule
          uri: http://localhost:8082/
          predicates:
            - Path=/consumer/**
        - id: eurekaService
          uri: http://localhost:8084
          predicates:
            - Path=/**